// MASTER CURRICULUM STANDARDS
// Source: User provided text block (Jan 26, 2026) + Previous Standards

export const MASTER_CURRICULUM = {
    "Algebra 1A": [
        "1.1.3 Quiz: Rational and Irrational Numbers",
        "1.2.3 Quiz: Algebraic Properties and Expressions",
        "1.3.3 Quiz: Solving Linear Equations",
        "1.3.4 Practice: Modeling: Solving Linear Equations",
        "1.4.3 Test (CST): Foundations of Algebra",
        "2.1.3 Quiz: Solving Multistep Linear Equations",
        "2.1.4 Practice: Modeling: Multistep Linear Equations",
        "2.2.3 Quiz: Solving Linear Inequalities",
        "2.3.3 Quiz: Literal Equations",
        "2.4.3 Quiz: Measurement and Units",
        "2.4.4 Journal: Measurement and Units",
        "2.6.3 Test (CST): Solving Equations and Inequalities",
        "3.1.3 Quiz: Domain and Range",
        "3.2.3 Quiz: Identifying Functions",
        "3.3.3 Quiz: Graphs of Functions",
        "3.4.3 Quiz: Adding and Subtracting Functions",
        "3.5.3 Test (CST): Functions",
        "4.0.0-A Custom (EC): Slope-Intercept/Linear Inequalities Extra Credit",
        "4.1.3 Quiz: Slope",
        "4.1.4 Journal: Slope",
        "4.2.3 Quiz: Slope-Intercept Equation of a Line",
        "4.2.4 Practice: Modeling: Slope-Intercept Equation of a Line",
        "4.3.3 Quiz: Point-Slope Equation of a Line",
        "4.4.3 Quiz: Parallel and Perpendicular Lines",
        "4.5.3 Quiz: Linear Inequalities",
        "4.6.3 Test (CST): Linear Equations",
        "5.1.3 Quiz: Two-Variable Systems: Graphing",
        "5.2.3 Quiz: Two-Variable Systems: Substitution",
        "5.3.3 Quiz: Two-Variable Systems: Elimination",
        "5.3.4 Journal: Two-Variable Systems: Elimination",
        "5.4.3 Quiz: Two-Variable Systems of Inequalities",
        "5.5.3 Test (CST): Systems of Linear Equations",
        "6.1.3 Quiz: Exponents",
        "6.2.3 Quiz: Exponential Functions",
        "6.2.4 Practice: Modeling: Exponential Functions",
        "6.3.3 Quiz: Graphs of Exponential Functions",
        "6.3.4 Journal: Graphs of Exponential Functions",
        "6.4.3 Test (CST): Exponents and Exponential Functions",
        "7.1.3 Quiz: Arithmetic Sequences",
        "7.1.4 Journal: Arithmetic Sequences",
        "7.2.3 Quiz: Geometric Sequences",
        "7.2.4 Practice: Modeling: Geometric Sequences",
        "7.4.3 Quiz: Exponential and Linear Growth",
        "7.5.3 Test (CST): Sequences and Functions",
        "8.1.2 Exam: Semester 1 Exam"
    ],
    "Algebra 1B": [
        "1.1.3 Quiz: What Is a Polynomial?",
        "1.2.3 Quiz: Adding and Subtracting Polynomials",
        "1.3.3 Quiz: Multiplying Binomials",
        "1.3.4 Practice: Modeling: Multiplying Binomials",
        "1.5.3 Test (CST): Polynomials",
        "2.1.3 Quiz: GCF and Factoring by Grouping",
        "2.2.3 Quiz: Factoring x^2 + bx + c",
        "2.3.3 Quiz: Factoring ax^2 + bx + c",
        "2.4.3 Quiz: Special Cases",
        "2.5.3 Quiz: Factoring and Graphing",
        "2.6.3 Test (CST): Factoring Polynomials",
        "3.1.3 Quiz: Solving Quadratic Equations",
        "3.2.4 Journal: Completing the Square",
        "3.3.3 Quiz: The Quadratic Formula",
        "3.4.3 Quiz: Graphs of Quadratic Functions",
        "3.5.3 Quiz: Nonlinear Systems of Equations",
        "3.6.3 Quiz: Linear, Quadratic, and Exponential Functions",
        "3.6.4 Practice: Modeling: Linear, Quadratic, and Exponential Functions",
        "3.8.3 Test (CST): Quadratic Equations and Functions",
        "4.1.3 Quiz: Inverses",
        "4.2.3 Quiz: Parent Functions",
        "4.3.3 Quiz: Shifting Functions",
        "4.3.4 Journal: Shifting Functions",
        "4.4.3 Quiz: Stretching and Compressing Functions",
        "4.4.4 Practice: Modeling: Stretching and Compressing Functions",
        "4.5.3 Quiz: Transformations of Parent Functions",
        "4.6.3 Test (CST): Undoing Functions and Moving Them Around",
        "5.1.3 Quiz: Measures of Center and Spread",
        "5.2.3 Quiz: Dot Plots, Box Plots, and Histograms",
        "5.2.4 Practice: Modeling: Dot Plots, Box Plots, and Histograms",
        "5.3.3 Quiz: Describing Distributions",
        "5.3.4 Journal: Describing Distributions",
        "5.4.3 Quiz: Two-Way Frequency Tables",
        "5.5.3 Test (CST): Descriptive Statistics",
        "6.1.3 Quiz: Two-Variable Data and Scatterplots",
        "6.2.3 Quiz: Fitting Linear Models to Data",
        "6.3.3 Quiz: Nonlinear Models",
        "6.4.3 Test (CST): Data and Mathematical Modeling",
        "7.1.2 Exam: Semester 2 Exam"
    ],
    "Algebra 2A": [
        "1.1.3 Quiz: Algebraic Expressions",
        "1.2.3 Quiz: Solving Linear Equations",
        "1.3.3 Quiz: Solving Absolute Value Equations",
        "1.4.3 Quiz: Solving Inequalities",
        "1.5.3 Quiz: Literal Equations and Formulas",
        "1.6.2 Test (CST): Expressions, Equations, and Inequalities",
        "2.1.3 Quiz: Functions",
        "2.2.3 Quiz: Graphing Functions",
        "2.3.3 Quiz: Transforming Functions",
        "2.4.3 Quiz: Combining Functions",
        "2.5.3 Quiz: Inverse Functions",
        "2.6.2 Test (CST): Functions and Relations",
        "3.1.3 Quiz: Binomial Factors of Trinomials",
        "3.1.4 Quiz: Factoring Trinomials",
        "3.2.3 Quiz: Factoring Trinomials (Basic)",
        "3.3.3 Quiz: Factoring a Difference of Squares",
        "3.3.4 Quiz: Factoring Perfect Square Trinomials",
        "3.4.3 Quiz: Factoring with the Zero Product Rule",
        "3.4.4 Quiz: Converting Quadratics to Standard Form",
        "3.4.5 Quiz: Quadratics with Perfect Square Trinomials",
        "3.6.4 Quiz: The Quadratic Formula",
        "3.7.3 Quiz: Graphs of Quadratic Functions",
        "3.8.3 Quiz: Imaginary Numbers",
        "3.8.4 Quiz: Operations on Complex Numbers",
        "3.8.5 Quiz: Quadratics With Complex Solutions",
        "3.9.2 Test (CST): Quadratic Functions",
        "4.1.3 Quiz: Linear Systems of Equations",
        "4.2.3 Quiz: Nonlinear Systems of Equations",
        "4.3.3 Quiz: Linear Systems of Inequalities",
        "4.4.2 Test (CST): Systems of Equations and Inequalities",
        "5.1.3 Quiz: Polynomial Basics",
        "5.2.3 Quiz: Polynomial Functions",
        "5.3.3 Quiz: Synthetic Division",
        "5.4.3 Quiz: Remainder and Factor Theorems",
        "5.4.4 Quiz: Factoring Polynomials Completely",
        "5.6.3 Quiz: Graphing Polynomial Functions",
        "5.9.3 Quiz: Transformations of Polynomial Functions",
        "5.10.2 Test (CST): Polynomial Functions",
        "6.1.2 Exam: Semester 1 Exam"
    ],
    "Algebra 2B": [
        "1.1.3 Quiz: Proportions",
        "1.2.3 Quiz: Rational Expressions",
        "1.3.3 Quiz: Simplifying Rational Expressions",
        "1.4.3 Quiz: Multiplying Rational Expressions",
        "1.4.4 Quiz: Dividing Rational Expressions",
        "1.5.3 Quiz: Adding and Subtracting Rational Expressions",
        "1.8.3 Quiz: Solving Rational Equations",
        "1.9.3 Quiz: Finding Vertical Asymptotes",
        "1.10.3 Quiz: Graphing Rational Functions",
        "1.11.2 Test (CST): Rational Expressions and Functions",
        "2.1.3 Quiz: Simplifying Products of Radicals",
        "2.1.4 Quiz: Simplifying Quotients of Radicals",
        "2.2.3 Quiz: Multiplying Radicals",
        "2.2.4 Quiz: Dividing Radicals",
        "2.3.3 Quiz: Adding and Subtracting Radicals",
        "2.4.3 Quiz: Rationalizing Denominators",
        "2.5.3 Quiz: Solving Radical Functions",
        "2.7.3 Quiz: Fractional Exponents — Part 1",
        "2.7.4 Quiz: Fractional Exponents — Part 2",
        "2.10.2 Test (CST): Radical Expressions and Functions",
        "3.1.3 Quiz: Geometric Sequences",
        "3.2.3 Quiz: Evaluating Exponential Functions",
        "3.2.4 Quiz: Calculating Exponential Growth",
        "3.4.3 Quiz: Graphs of Exponential Functions",
        "3.5.3 Quiz: Logarithmic Functions",
        "3.6.3 Quiz: Graphs of Logarithmic Functions",
        "3.7.3 Quiz: Equivalent Exponential Expressions",
        "3.7.4 Quiz: Equivalent Logarithmic Expressions",
        "3.7.5 Quiz: Evaluating Logarithms",
        "3.8.3 Quiz: Solving Exponential Equations",
        "3.9.3 Quiz: Solving Logarithmic Equations",
        "3.12.2 Test (CST): Exponential and Logarithmic Functions",
        "4.1.3 Quiz: Using Data to Make Inferences",
        "4.2.3 Quiz: Using Probability to Make Decisions",
        "4.3.3 Quiz: Simulation and Modeling with Data",
        "4.6.2 Test (CST): Statistical Analysis",
        "6.1.2 Exam: Semester 2 Exam"
    ],
    "Art Appreciation": [
        "1.1.1 Discuss: Question Everything",
        "1.1.4 Quiz: Broad Strokes: Principles of Painting",
        "1.2.3 Quiz: Influences Real and Imaginary",
        "1.2.4 Journal: The Way I See It",
        "1.3.3 Quiz: How to Critique",
        "1.3.4 Practice: Be the Critic",
        "1.4.2 Test (CST): Introduction to Painting",
        "2.1.1 Discuss: Question Everything",
        "2.1.4 Quiz: A Long, Long Time Ago",
        "2.2.3 Quiz: Medieval Times",
        "2.2.4 Journal: The Way I See It",
        "2.3.3 Quiz: Painting in the 15th Century",
        "2.3.4 Practice: Be the Critic",
        "2.4.2 Test (CST): Prehistoric to Late Middle Ages",
        "3.1.1 Discuss: Question Everything",
        "3.1.4 Quiz: Early and High Renaissance",
        "3.2.2 Quiz: High Renaissance Masters",
        "3.2.3 Journal: The Way I See It",
        "3.3.4 Quiz: Northern Renaissance",
        "3.3.5 Practice: Be the Critic",
        "3.4.2 Test (CST): The Renaissance",
        "4.1.1 Discuss: Question Everything",
        "4.1.4 Quiz: The Early Baroque Period",
        "4.2.3 Quiz: The Late Baroque Period",
        "4.2.4 Journal: The Way I See It",
        "4.3.3 Quiz: Art in 18th-Century Europe",
        "4.3.4 Practice: Be the Critic",
        "4.4.2 Test (CST): Baroque and Rococo",
        "5.1.1 Discuss: Question Everything",
        "5.1.5 Quiz: 19th-Century Art in Five Movements",
        "5.2.3 Quiz: A New Way of Seeing: 20th-Century Art",
        "5.2.4 Journal: The Way I See It",
        "5.3.2 Quiz: Museums and the Art Market",
        "5.3.3 Practice: Be the Critic",
        "5.4.2 Test (CST): Modernity in the 19th and 20th Centuries",
        "6.4.1 Practice: Art Is What You Make It"
    ],
    "Biology A": [
        "1.1.2 Quiz: The Nature of Science",
        "1.1.5 Journal: What Is a Biologist?",
        "1.2.4 Quiz: Science, Society, and Technology",
        "1.2.5 Practice: Themes in Biology",
        "1.3.2 Quiz: The Scientific Process",
        "1.4.3 Test (TST): Teacher-Scored Unit Test",
        "2.1.2 Quiz: Common Elements in Living Things",
        "2.1.5 Journal: Chemistry in Biology",
        "2.2.2 Quiz: Carbohydrates",
        "2.2.4 Quiz: Nucleic Acids and Lipids",
        "2.3.2 Quiz: Proteins and Enzymes",
        "2.3.4 Quiz: Water",
        "2.4.2 Quiz: Enzyme Action: How Clean Is Your Laundry?",
        "2.5.3 Test (TST): Teacher-Scored Unit Test",
        "3.1.2 Quiz: General Structure of the Cell",
        "3.1.4 Quiz: Detailed Structure of the Cell",
        "3.1.5 Journal: Chloroplasts",
        "3.2.2 Quiz: Cell Membrane Structure",
        "3.2.4 Quiz: Cellular Transport",
        "3.3.2 Quiz: Specialized Cells and Tissues",
        "3.3.4 Quiz: Cell Differentiation and Stem Cells",
        "3.3.5 Practice: Cells",
        "3.4.2 Quiz: Why Are Cells So Small?",
        "3.5.3 Test (TST): Teacher-Scored Unit Test",
        "4.1.2 Quiz: Photosynthesis Introduction",
        "4.1.4 Quiz: Process of Photosynthesis",
        "4.1.5 Journal: Your Sources of Oxygen",
        "4.2.2 Quiz: Respiration Introduction",
        "4.2.4 Quiz: Process of Respiration",
        "4.3.2 Quiz: Relationships in an Ecosystem",
        "4.3.4 Quiz: Energy in the Food Web",
        "4.3.5 Practice: Matter and Energy",
        "4.4.2 Quiz: Anaerobic Respiration of Yeast",
        "4.5.3 Test (TST): Teacher-Scored Unit Test",
        "5.1.2 Quiz: Water and Oxygen Cycles",
        "5.1.4 Quiz: Carbon and Nitrogen Cycles",
        "5.1.5 Journal: Your Contribution",
        "5.2.2 Quiz: Climate Change",
        "5.2.4 Quiz: Human Population",
        "5.3.5 Practice: Solutions for the Future",
        "5.5.3 Test (TST): Teacher-Scored Unit Test",
        "6.1.3 Final Exam: Semester 1 Exam"
    ],
    "Biology B": [
        "1.1.2 Quiz: Organization of DNA",
        "1.1.4 Quiz: Mitosis",
        "1.1.5 Journal: Your Traits",
        "1.2.2 Quiz: Meiosis",
        "1.2.4 Quiz: Principles of Heredity",
        "1.3.2 Quiz: Basics of Mendelian Genetics",
        "1.3.4 Quiz: Predicting Genetic Outcomes",
        "1.3.5 Practice: DNA and Heredity",
        "1.4.2 Quiz: DNA Fingerprinting",
        "1.5.3 Test (TST): Teacher-Scored Unit Test",
        "2.1.2 Quiz: DNA Replication",
        "2.1.4 Quiz: Viruses and Bacteria",
        "2.1.5 Journal: Nucleic Acids",
        "2.2.2 Quiz: Transcription",
        "2.2.4 Quiz: Translation",
        "2.3.2 Quiz: Genetic Mutations",
        "2.3.4 Quiz: DNA Technology",
        "2.3.5 Practice: DNA to Protein",
        "2.4.2 Quiz: Mutations",
        "2.5.3 Test (TST): Teacher-Scored Unit Test",
        "3.1.2 Quiz: Ecosystems and Biomes",
        "3.1.4 Quiz: Stability and Change in an Ecosystem",
        "3.1.5 Journal: Your Ecosystem",
        "3.2.2 Quiz: Population Structure",
        "3.2.4 Quiz: Population Dynamics",
        "3.3.2 Quiz: Variation and Adaptation",
        "3.3.4 Quiz: Natural Selection",
        "3.3.5 Practice: Adaptation and Natural Selection",
        "3.4.2 Quiz: Natural Selection",
        "3.5.3 Test (TST): Teacher-Scored Unit Test",
        "4.1.2 Quiz: Mechanism for Evolution",
        "4.1.4 Quiz: Evidence for Evolution",
        "4.1.5 Journal: Theories and Laws",
        "4.2.2 Quiz: Speciation",
        "4.2.4 Quiz: Methods for Classification",
        "4.3.2 Quiz: Life on Earth",
        "4.3.4 Quiz: Plants and Animals",
        "4.3.5 Practice: Diversity of Life",
        "4.4.2 Quiz: Bone Comparison",
        "4.5.3 Test (TST): Teacher-Scored Unit Test",
        "6.1.3 Final Exam: Semester 2 Exam"
    ],
    "College and Career Preparation I": [
        "1.1.1 Discuss: Get Acquainted",
        "1.1.4 Quiz: Assess Your Learning",
        "1.1.7 Quiz: Assess Your Learning",
        "1.2.4 Quiz: Assess Your Learning",
        "1.2.5 Journal: Thinking about College",
        "1.3.3 Quiz: Assess Your Learning",
        "1.3.4 Practice: Discovering More Resources",
        "1.5.2 Test (CST): Prepare for College in High School",
        "2.1.4 Practice: Look into Some Colleges",
        "2.2.3 Quiz: Assess Your Learning",
        "2.2.4 Journal: Programs and Degrees",
        "2.3.2 Quiz: Assess Your Learning",
        "2.4.2 Test (CST): College Knowledge",
        "3.3.2 Quiz: Assess Your Learning",
        "3.4.2 Test (CST): Testing and Assessments",
        "4.1.4 Quiz: Assess Your Learning",
        "4.1.5 Practice: Helpful Resources",
        "4.2.2 Quiz: Assess Your Learning",
        "4.4.2 Test (CST): Financial Aid",
        "5.1.2 Quiz: Assess Your Learning",
        "5.1.3 Journal: Relating to the Clusters",
        "5.3.2 Quiz: Assess Your Learning",
        "5.4.2 Test (CST): Career Opportunities",
        "6.1.2 Exam: Exam"
    ],
    "English 10A": [
        "1.1.4 Quiz: Understand Writing Versus Speech",
        "1.1.6 Quiz: Two Readings about Pluto",
        "1.1.8 Quiz: Analyze Expository Writing",
        "1.1.10 Practice: Complete Your Assignment",
        "1.2.2 Quiz: Understand the Elements of Rhetoric",
        "1.2.4 Quiz: From Julius Caesar by William Shakespeare",
        "1.2.7 Quiz: Analyze Using Rhetoric to Sway an Audience",
        "1.2.9 Project: Complete Your Assignment",
        "1.3.3 Quiz: Understand Narrative and Plot",
        "1.3.5 Quiz: The Story of My Life by Helen Keller",
        "1.3.7 Quiz: Analyze The Story and Its Narrator",
        "1.3.9 Practice: Complete Your Assignment",
        "1.4.4 Test (TST): The Written Word",
        "2.1.4 Quiz: Understand Conflict and Plot",
        "2.1.6 Quiz: American Born Chinese, Part 1",
        "2.1.8 Quiz: Analyze Multiple Plots",
        "2.1.10 Practice: Complete Your Assignment",
        "2.2.2 Quiz: Understand Types of Characters",
        "2.2.4 Quiz: American Born Chinese, Part 2",
        "2.2.5 Discuss: Think It Through, Talk It Out",
        "2.2.7 Quiz: Analyze The Character Arc",
        "2.2.9 Practice: Complete Your Assignment",
        "2.3.3 Quiz: Understand Mood",
        "2.3.5 Quiz: A Visit of Charity by Eudora Welty",
        "2.3.7 Quiz: Analyze Pacing and Dialogue",
        "2.3.9 Practice: Complete Your Assignment",
        "2.4.4 Test (TST): The Story",
        "3.1.4 Quiz: Understand The Meaning of Theme",
        "3.1.6 Quiz: To Build a Fire by Jack London",
        "3.1.8 Quiz: Analyze Interpretation",
        "3.1.10 Practice: Complete Your Assignment",
        "3.2.2 Quiz: Understand Types of Figurative Language",
        "3.2.4 Quiz: Various Poems",
        "3.2.5 Discuss: Think It Through, Talk It Out",
        "3.2.7 Quiz: Analyze The Meanings of Words",
        "3.2.9 Practice: Complete Your Assignment",
        "3.3.3 Quiz: Understand Culture and Literature",
        "3.3.5 Quiz: The Ramayana and an Illustration",
        "3.3.7 Quiz: Analyze Literary Tradition and Medium",
        "3.3.9 Practice: Complete Your Assignment",
        "3.4.4 Test (TST): Literary Criticism",
        "4.1.4 Quiz: Understand The Research Question",
        "4.1.6 Quiz: Fast Food Nation, Part 1",
        "4.1.8 Quiz: Analyze Evaluating Credibility",
        "4.1.10 Practice: Complete Your Assignment",
        "4.2.2 Quiz: Understand The Role of the Researcher",
        "4.2.4 Quiz: Fast Food Nation, Part 2",
        "4.2.5 Discuss: Think It Through, Talk It Out",
        "4.2.7 Quiz: Analyze Incorporating Source Material",
        "4.2.9 Practice: Complete Your Assignment",
        "4.3.3 Quiz: Understand Review and Revision",
        "4.3.5 Quiz: Fast Food Nation, Part 3",
        "4.3.7 Quiz: Analyze Revising by Criteria",
        "4.3.9 Practice: Complete Your Assignment",
        "4.4.4 Test (TST): The Research Paper",
        "5.1.3 Final Exam: Wrap Up"
    ],
    "English 10B": [
        "1.1.4 Quiz: Understand Organizing Information",
        "1.1.6 Quiz: Three Uniquely Organized Documents",
        "1.1.8 Quiz: Analyze Organizing Paragraphs",
        "1.2.3 Quiz: Understand Clarity",
        "1.2.5 Quiz: How to Jump-Start a Car Battery",
        "1.2.7 Quiz: Analyze Page Layout",
        "1.2.9 Practice: Complete Your Assignment",
        "1.3.2 Quiz: Understand Audience Sensitivity",
        "1.3.4 Quiz: Two Sample Cover Letters",
        "1.3.5 Discuss: Think It Through, Talk It Out",
        "1.3.7 Quiz: Analyze Strengths and Weaknesses of Cover Letters",
        "1.3.9 Practice: Complete Your Assignment",
        "1.4.4 Test (TST): Practical Documents",
        "2.1.4 Quiz: Understand How to Persuade with Tone and Diction",
        "2.1.6 Quiz: On Indian Removal and Samuel's Memory",
        "2.1.8 Quiz: Analyze Contrasting Tones",
        "2.1.10 Practice: Complete Your Assignment",
        "2.2.3 Quiz: Understand Journalism as Persuasion",
        "2.2.5 Quiz: Three Stories about Hurricane Katrina",
        "2.2.7 Quiz: Analyze Bias in Media",
        "2.2.9 Practice: Complete Your Assignment",
        "2.3.2 Quiz: Understand Stories with Purpose",
        "2.3.4 Quiz: Top of the Food Chain by T. C. Boyle",
        "2.3.5 Discuss: Think It Through, Talk It Out",
        "2.3.7 Quiz: Analyze Rhetoric in Narratives",
        "2.3.9 Practice: Complete Your Assignment",
        "2.4.3 Test (CST): Persuasive Texts",
        "2.4.4 Test (TST): Persuasive Texts",
        "3.1.4 Quiz: Understand Rhetoric in Speeches",
        "3.1.6 Quiz: Speeches by Two Presidents",
        "3.1.8 Quiz: Analyze Evidence, Reasoning, and Point of View in Speeches",
        "3.1.10 Practice: Complete Your Assignment",
        "3.2.3 Quiz: Understand the Role of the Speaker",
        "3.2.5 Quiz: FDR's Four Freedoms Speech",
        "3.2.7 Quiz: Analyze Themes and Their Uses",
        "3.2.9 Project: Complete Your Assignment",
        "3.3.2 Quiz: Understand Professionalism in Speeches",
        "3.3.4 Quiz: Speeches by Al Gore and Dan Pink",
        "3.3.7 Quiz: Analyze Adapting to Audience and Context",
        "3.3.9 Project: Complete Your Assignment",
        "3.4.3 Test (CST): The Speech",
        "3.4.4 Test (TST): The Speech",
        "4.1.4 Quiz: Understand Types of Claims",
        "4.1.6 Quiz: Compulsory Voting: An Idea Whose Time Has Come",
        "4.1.8 Quiz: Analyze Formulating an Argument",
        "4.1.10 Practice: Complete Your Assignment",
        "4.2.2 Quiz: Understand Anticipating Counterclaims",
        "4.2.4 Quiz: A Defense of Veganism",
        "4.2.5 Discuss: Think It Through, Talk It Out",
        "4.2.7 Quiz: Analyze Writing with Civility",
        "4.2.9 Practice: Complete Your Assignment",
        "4.3.3 Quiz: Understand How to Provide Peer Review",
        "4.3.6 Quiz: Analyze Revision Strategies",
        "4.3.8 Quiz: Prepare an Argumentative Research Paper, Part III",
        "4.3.9 Practice: Complete Your Assignment",
        "4.4.3 Test (CST): Researched Argumentation",
        "4.4.4 Test (TST): Researched Argumentation",
        "5.1.3 Final Exam: Wrap Up"
    ],
    "English 11A": [
        "1.1.4 Quiz: Understand Rhetoric",
        "1.1.6 Quiz: Patrick Henry and Thomas Paine",
        "1.1.8 Quiz: Analyze Rhetoric",
        "1.1.10 Practice: Complete Your Assignment",
        "1.2.2 Quiz: Understand the Declaration of Independence",
        "1.2.4 Quiz: The Declaration of Independence and an Essay",
        "1.2.5 Discuss: Think It Through, Talk It Out",
        "1.2.7 Quiz: Analyze the Declaration",
        "1.2.9 Practice: Complete Your Assignment",
        "1.3.3 Quiz: Understand the Constitution",
        "1.4.4 Test (TST): The American Revolution",
        "2.1.4 Quiz: Understand Poetry",
        "2.1.6 Quiz: Whitman and Dickinson",
        "2.1.8 Quiz: Analyze Poetry",
        "2.1.10 Practice: Complete Your Assignment",
        "2.2.3 Quiz: Understand Gothic Writing",
        "2.2.5 Quiz: The Raven and The Philosophy of Composition",
        "2.2.7 Quiz: Analyze Poetry Readings",
        "2.2.9 Practice: Complete Your Assignment",
        "2.3.2 Quiz: Understand Transcendentalism",
        "2.3.4 Quiz: Resistance to Civil Government",
        "2.3.5 Discuss: Think It Through, Talk It Out",
        "2.3.7 Quiz: Analyze Resistance to Civil Government",
        "2.3.9 Practice: Complete Your Assignment",
        "2.4.4 Test (TST): Wrap-Up: Romanticism and Transcendentalism",
        "3.1.3 Quiz: Understand Mark Twain and Satire",
        "3.1.5 Quiz: Life on the Mississippi",
        "3.1.6 Discuss: Think It Through, Talk It Out",
        "3.1.8 Quiz: Analyze Life on the Mississippi",
        "3.1.10 Practice: Complete Your Assignment",
        "3.2.3 Quiz: Understand the Civil War",
        "3.2.5 Quiz: Narrative of the Life of Frederick Douglass",
        "3.2.7 Quiz: Analyze Narrative of the Life of Frederick Douglass",
        "3.2.9 Project: Complete Your Assignment",
        "3.3.3 Quiz: Understand Westward Expansion",
        "3.4.4 Test (TST): Wrap-Up: The American Narrative",
        "4.1.4 Quiz: Understand the American Dream",
        "4.1.10 Practice: Complete Your Assignment",
        "4.2.2 Quiz: Understand the Jazz Age",
        "4.2.4 Quiz: The Great Gatsby, Part I",
        "4.2.5 Discuss: Think It Through, Talk It Out",
        "4.2.7 Quiz: Analyze The Great Gatsby",
        "4.2.9 Practice: Complete Your Assignment",
        "4.3.3 Quiz: Understand the Message of Gatsby",
        "4.3.5 Quiz: The Great Gatsby, Part II",
        "4.3.7 Quiz: Analyze The Great Gatsby",
        "4.3.9 Project: Complete Your Assignment",
        "4.4.4 Test (TST): Wrap-Up: Modernism and The American Dream",
        "5.1.3 Final Exam: Wrap Up"
    ],
    "English 9A": [
        "1.1.3 Quiz: Understand the Shape of a Story",
        "1.1.5 Quiz: The Monkey's Paw by W. W. Jacobs",
        "1.1.6 Discuss: Creating Tension",
        "1.1.8 Quiz: Analyze the Shape of a Story",
        "1.1.10 Practice: Complete Your Assignment",
        "1.2.3 Quiz: Understand Setting, Character, and Dialogue",
        "1.2.5 Quiz: The Chrysanthemums by John Steinbeck",
        "1.2.7 Quiz: Analyze Setting, Character, and Dialogue",
        "1.2.9 Practice: Complete Your Assignment",
        "1.3.3 Quiz: Understand Theme and Point of View",
        "1.3.5 Quiz: The Yellow Wallpaper by Charlotte Perkins Gilman",
        "1.3.7 Quiz: Analyze Theme and Point of View",
        "1.3.9 Practice: Complete Your Assignment",
        "1.4.4 Test (TST): The Short Story, Part 1",
        "2.1.4 Quiz: Understand Characters through Symbols",
        "2.1.6 Quiz: Everyday Use by Alice Walker",
        "2.1.8 Quiz: Analyze Characters Through Symbols",
        "2.1.10 Project: Complete Your Assignment",
        "2.2.9 Practice: Complete Your Assignment",
        "2.3.3 Quiz: Understand Gothic Elements in Literature",
        "2.3.5 Quiz: The Black Cat by Edgar Allan Poe",
        "2.3.7 Quiz: Analyze Gothic Elements in Literature",
        "2.3.9 Practice: Complete Your Assignment",
        "2.4.4 Test (TST): The Short Story, Part 2",
        "3.1.4 Quiz: Understand Poetic Language",
        "3.1.6 Quiz: Three Poems",
        "3.1.8 Quiz: Analyze Poetic Language",
        "3.1.10 Project: Complete Your Assignment",
        "3.2.2 Quiz: Understand the Functions of the Form",
        "3.2.4 Quiz: Three Poems",
        "3.2.5 Discuss: Words versus Pictures",
        "3.2.7 Quiz: Analyze the Functions of the Form",
        "3.2.9 Practice: Complete Your Assignment",
        "3.3.3 Quiz: Understand How Artists Build on Source Material",
        "3.3.5 Quiz: Two Poems, One Painting",
        "3.3.7 Quiz: Analyze How Artists Build on Source Material",
        "3.3.9 Practice: Complete Your Assignment",
        "3.4.4 Test (TST): Poetry",
        "4.1.4 Quiz: Understand Translations",
        "4.1.6 Quiz: The Metamorphosis by Franz Kafka, Part 1",
        "4.1.8 Quiz: Analyze the Translation of Kafka's The Metamorphosis",
        "4.1.10 Practice: Complete Your Assignment",
        "4.2.3 Quiz: Understand the Context of Stories",
        "4.2.5 Quiz: The Metamorphosis by Franz Kafka, Part 2",
        "4.2.7 Quiz: Analyze Themes in Life and Literature",
        "4.2.9 Practice: Complete Your Assignment",
        "4.3.2 Quiz: Understand Transformation",
        "4.3.4 Quiz: The Metamorphosis by Franz Kafka, Part 3",
        "4.3.5 Discuss: The Second Metamorphosis",
        "4.3.7 Quiz: Analyze the Resolution of The Metamorphosis",
        "4.3.9 Practice: Complete Your Assignment",
        "4.4.4 Test (TST): The Novella: Franz Kafka's The Metamorphosis",
        "5.1.3 Final Exam: Semester Exam"
    ],
    "English 9B": [
        "1.1.4 Quiz: Understand Rhetoric",
        "1.1.6 Quiz: An Essay from Beyond the Wall by Edward Abbey",
        "1.1.8 Quiz: Analyze Rhetoric",
        "1.1.10 Practice: Complete Your Assignment",
        "1.2.2 Quiz: Understand Bias and Reasoning",
        "1.2.9 Practice: Complete Your Assignment",
        "1.3.3 Quiz: Understand Different Argument Types",
        "1.3.5 Quiz: An Indian Father's Plea by Medicine Grizzlybear Lake",
        "1.3.7 Quiz: Analyze a Different Type of Argument",
        "1.3.9 Project: Complete Your Assignment",
        "1.4.4 Test (TST): The Rhetoric of Argument",
        "2.1.3 Quiz: Understand How Word Choice and Context Matter",
        "2.1.5 Quiz: Speech After Being Convicted of Voting by Susan B. Anthony",
        "2.1.6 Discuss: Suffrage",
        "2.1.8 Quiz: Analyze How Word Choice and Context Matter",
        "2.1.10 Project: Complete Your Assignment",
        "2.2.3 Quiz: Understand the Quest for Civil Rights",
        "2.2.5 Quiz: Nobel Acceptance Speech by Martin Luther King Jr.",
        "2.2.7 Quiz: Analyze the Quest for Civil Rights",
        "2.2.9 Project: Complete Your Assignment",
        "2.3.3 Quiz: Understand the Quest for Human Rights",
        "2.3.5 Quiz: The Perils of Indifference by Elie Wiesel",
        "2.3.7 Quiz: Analyze the Quest for Human Rights",
        "2.3.9 Practice: Complete Your Assignment",
        "2.4.4 Test (TST): The Rhetoric of Speeches",
        "3.1.4 Quiz: Understand Invasion Literature",
        "3.1.6 Quiz: The War of the Worlds by H. G. Wells",
        "3.1.8 Quiz: Analyze Invasion Literature",
        "3.1.10 Practice: Complete Your Assignment",
        "3.2.2 Quiz: Understand Assumptions of Truth",
        "3.2.4 Quiz: The War of the Worlds on the Radio",
        "3.2.5 Discuss: Could It Happen Again?",
        "3.2.7 Quiz: Analyze Assumptions of Truth",
        "3.2.9 Practice: Complete Your Assignment",
        "3.3.3 Quiz: Understand the Vulnerability to Media",
        "3.3.5 Quiz: Stories After the Fact",
        "3.3.7 Quiz: Analyze the Vulnerability to Media",
        "3.3.9 Practice: Complete Your Assignment",
        "3.4.4 Test (TST): Reinterpreting Fiction",
        "4.1.4 Quiz: Understand the World and Words of Shakespeare",
        "4.1.6 Quiz: Macbeth by William Shakespeare, Part 1",
        "4.1.8 Quiz: Analyze How Shakespeare Develops Character",
        "4.1.10 Practice: Complete Your Assignment",
        "4.2.2 Quiz: Understand the Supernatural in Macbeth",
        "4.2.4 Quiz: Macbeth by William Shakespeare, Part 2",
        "4.2.5 Discuss: Superstition Today",
        "4.2.7 Quiz: Analyze the Supernatural in Macbeth",
        "4.2.9 Practice: Complete Your Assignment",
        "4.3.3 Quiz: Understand the Tragic Hero",
        "4.3.5 Quiz: Macbeth by William Shakespeare, Part 3",
        "4.3.7 Quiz: Analyze Different Interpretations of Macbeth",
        "4.3.9 Project: Complete Your Assignment",
        "4.4.4 Test (TST): Drama: Shakespeare's Macbeth",
        "5.1.3 Final Exam: Semester Exam"
    ],
    "Environmental Science A": [
        "1.1.2 Quiz: The Nature of Science",
        "1.1.4 Quiz: The Practice of Science",
        "1.2.2 Quiz: Fields of Science",
        "1.2.4 Quiz: Applied Science and Technology",
        "1.2.5 Explore: GPS and GIS Technology",
        "1.2.6 Practice: Science and the Environment",
        "1.3.2 Quiz: Investigate Cycling of O<sub>2</sub> and CO<sub>2</sub>",
        "1.4.3 Test (TST): What Is Science?",
        "2.1.2 Quiz: The Oceans",
        "2.1.4 Quiz: Bodies of Freshwater",
        "2.1.6 Quiz: Movements of the Hydrosphere",
        "2.1.7 Practice: The Hydrosphere",
        "2.2.2 Quiz: Earth's Crust and Landforms",
        "2.2.4 Quiz: Soil Composition and Structure",
        "2.2.6 Quiz: Movements of Land and Soil",
        "2.2.7 Explore: Earthquake Prediction and Readiness",
        "2.3.2 Quiz: Structure and Movements of the Atmosphere",
        "2.3.4 Quiz: Weather and Climate",
        "2.3.5 Practice: The Atmosphere",
        "2.4.2 Quiz: Investigate Weathering and Erosion",
        "2.5.3 Test (TST): Earth's Physical Systems",
        "3.1.2 Quiz: Biotic and Abiotic Factors",
        "3.1.4 Quiz: Biogeochemical Cycles",
        "3.1.5 Practice: Nature of the Biosphere",
        "3.2.2 Quiz: Matter and Energy",
        "3.2.4 Quiz: The Flow of Matter and Energy",
        "3.2.5 Practice: Matter and Energy in the Biosphere",
        "3.3.2 Quiz: Terrestrial Biomes",
        "3.3.4 Quiz: Aquatic Ecosystems",
        "3.3.6 Quiz: Land Ecosystems",
        "3.3.7 Explore: The Importance of Coral Reefs",
        "3.4.2 Quiz: Investigate Using a Dichotomous Key",
        "3.5.3 Test (TST): The Biosphere",
        "4.1.2 Quiz: Characteristics of Populations",
        "4.1.4 Quiz: Population Growth",
        "4.1.5 Practice: Populations",
        "4.2.2 Quiz: What Is a Biological Community?",
        "4.2.4 Quiz: Species Interactions",
        "4.2.6 Quiz: Community Structure",
        "4.2.7 Practice: Communities",
        "4.3.2 Quiz: Natural Disturbances and Succession",
        "4.3.4 Quiz: Evolution and Biodiversity",
        "4.3.5 Explore: Biodiversity Hot Spots",
        "4.4.2 Quiz: Investigate Cycling of Matter and Energy",
        "4.5.3 Test (TST): Ecology",
        "5.1.3 Final Exam: Semester 1 Teacher-Scored Exam"
    ],
    "Environmental Science B": [
        "1.1.2 Quiz: Human Populations",
        "1.1.4 Quiz: Human Communities",
        "1.1.6 Explore: Public Health Policies",
        "1.2.2 Quiz: Land and Water Resources",
        "1.2.4 Quiz: Mineral and Energy Resources",
        "1.2.6 Quiz: Biological Resources",
        "1.2.7 Practice: Earth's Natural Resources",
        "1.3.2 Quiz: Agriculture, Forestry, and Fishing",
        "1.3.4 Quiz: Mining and Drilling",
        "1.3.6 Quiz: Recreation, Conservation, and Urban Development",
        "1.3.7 Practice: Land Use and Its Effects",
        "1.4.2 Quiz: Investigate Resource Consumption",
        "1.5.3 Test (TST): Humans and the Environment",
        "2.1.2 Quiz: Renewable Resources",
        "2.1.4 Quiz: Nonrenewable Resources",
        "2.1.6 Quiz: Alternative Energy Resources",
        "2.1.7 Practice: Resource Availability",
        "2.2.2 Quiz: Water, Air, and Land Pollution",
        "2.2.4 Quiz: Waste Management",
        "2.2.5 Practice: Pollution and Waste Management",
        "2.3.2 Quiz: Climate Change",
        "2.3.4 Quiz: Effects of Climate Change",
        "2.3.5 Explore: Effects of Climate Change",
        "2.4.2 Quiz: Investigate How Pollutants Affect Plants",
        "2.5.3 Test (TST): Environmental Challenges",
        "3.1.2 Quiz: The Tragedy of the Commons",
        "3.1.4 Quiz: Managing the Commons",
        "3.1.5 Practice: The Concept of the Commons",
        "3.2.2 Quiz: Protecting Water, Air, and Land",
        "3.2.4 Quiz: Protecting Endangered Species",
        "3.2.6 Explore: Species Survival Plans",
        "3.3.2 Quiz: Protecting Environmental Quality",
        "3.3.4 Quiz: Protecting Wildlife and Biodiversity",
        "3.3.5 Practice: Global Environmental Policies",
        "3.4.2 Quiz: Investigate Your Ecological Footprint",
        "3.5.3 Test (TST): Politics and the Environment",
        "4.1.5 Practice: The Global Community",
        "4.2.2 Quiz: Sustainable Food Production",
        "4.2.4 Quiz: Sustainable Resource Management",
        "4.2.6 Quiz: Sustainable Societal Development",
        "4.2.7 Explore: Carbon Dioxide Sequestration",
        "4.3.2 Quiz: Investigate Food Security",
        "4.4.3 Test (TST): Sustainability for the Future",
        "5.1.3 Final Exam: Semester 2 Teacher-Scored Exam"
    ],
    "Financial Literacy": [
        "1.1.2 Quiz: Building Good Spending Habits",
        "1.1.4 Quiz: Living Expenses",
        "1.1.5 Journal: Your Financial Goals and Spending Habits",
        "1.2.2 Quiz: Earning and Income",
        "1.2.4 Quiz: Paying Taxes",
        "1.2.5 Practice: Completing Tax Forms",
        "1.3.2 Quiz: Banking and Financial Statements",
        "1.3.4 Quiz: Digital Assets and Online Payment Methods",
        "1.3.5 Discuss: The Future of Cryptocurrency",
        "1.4.2 Test (CST): Earning and Spending",
        "2.1.2 Quiz: The Importance of Saving",
        "2.1.4 Quiz: Effects on Savings: Interest and Inflation",
        "2.1.5 Journal: Make a Savings Goal",
        "2.2.2 Quiz: Building Wealth",
        "2.2.4 Quiz: Types of Investments",
        "2.2.5 Practice: Comparing Investments",
        "2.3.2 Quiz: Saving for Retirement",
        "2.4.2 Test (CST): Savings and Investing",
        "3.1.2 Quiz: Types of Credit",
        "3.1.4 Quiz: Using Credit Wisely",
        "3.1.5 Practice: Making a Smart Automobile Purchase",
        "3.2.2 Quiz: Managing Your Debt",
        "3.3.2 Quiz: Monitoring Your Credit",
        "3.3.3 Discuss: Maintaining Good Credit",
        "3.4.2 Test (CST): Credit and Debt",
        "4.1.2 Quiz: Types of Insurance",
        "4.1.4 Quiz: Costs and Benefits of Insurance",
        "4.1.5 Explore: Buying Insurance",
        "4.2.2 Quiz: Consumer Protections",
        "4.2.4 Quiz: Fraud and Identity Theft",
        "4.2.5 Journal: Protecting Yourself",
        "4.3.2 Quiz: Estate Planning",
        "4.3.3 Practice: Protecting Your Future",
        "4.4.2 Test (CST): Protection of Assets",
        "6.1.3 Exam: Final Exam"
    ],
    "Geometry A": [
        "1.1.3 Quiz: Induction: The Search for Rules and Patterns",
        "1.2.3 Quiz: Deduction: Making a Case",
        "1.3.3 Quiz: The Look and Language of Logic",
        "1.4.2 Quiz: Introduction to Proofs",
        "1.5.3 Quiz: Basic Postulates in Geometry",
        "1.6.3 Quiz: Planes and the Space of Geometry",
        "1.7.3 Quiz: Intersecting Lines and Proofs",
        "1.8.3 Quiz: Parallel Lines and Proofs",
        "1.8.4 Journal: Consecutive Angle Theorem",
        "1.9.3 Test (CST): Foundations of Geometry",
        "2.1.3 Quiz: Naming Triangles by Angle Measures",
        "2.1.4 Quiz: Naming Triangles by Side Lengths",
        "2.1.5 Quiz: The Triangle Inequality Theorem",
        "2.2.3 Quiz: Angle Theorems",
        "2.2.4 Quiz: Exterior and Remote Interior Angles",
        "2.3.3 Quiz: Congruent Triangles",
        "2.3.4 Quiz: Properties of Congruence",
        "2.4.3 Quiz: Using Congruence Postulates",
        "2.4.4 Quiz: The AAS Theorem",
        "2.5.2 Quiz: Proofs of Congruence",
        "2.5.3 Journal: Proofs of Congruence",
        "2.6.3 Quiz: Similar Triangles",
        "2.7.3 Quiz: Similarity Theorems",
        "2.7.4 Practice: Modeling: Similarity Theorems",
        "2.8.3 Quiz: Isosceles and Equilateral Triangles",
        "2.8.4 Quiz: Scalene Triangles",
        "2.9.2 Quiz: Medians and Altitudes",
        "2.12.3 Test (CST): Triangles",
        "3.1.3 Quiz: The Pythagorean Theorem",
        "3.1.4 Journal: Proving the Pythagorean Theorem",
        "3.2.3 Quiz: Proving Right Triangle Congruence",
        "3.2.4 Quiz: Right Triangle Measurements",
        "3.3.3 Quiz: Similar Right Triangles",
        "3.3.4 Practice: Modeling: The Pool Table Problem",
        "3.4.3 Quiz: 45-45-90 Right Triangles",
        "3.4.4 Quiz: 30-60-90 Right Triangles",
        "3.5.3 Test (CST): Right Triangles",
        "4.1.3 Quiz: Trigonometric Ratios",
        "4.1.4 Practice: Modeling: Leaning Towers",
        "4.2.3 Quiz: Law of Cosines and Proofs",
        "4.4.3 Test (CST): Trigonometry",
        "5.1.3 Quiz: Angle Sums of a Polygon and Proofs",
        "5.2.3 Quiz: Parallelograms and Proofs",
        "5.3.3 Quiz: Tests for Parallelograms",
        "5.3.4 Practice: Modeling: Finding Parallelograms",
        "5.4.3 Quiz: Rectangles",
        "5.5.3 Quiz: Rhombi and Squares",
        "5.6.3 Quiz: Trapezoids",
        "5.6.4 Journal: The Stone Arch",
        "5.7.3 Test (CST): Quadrilaterals and Other Polygons",
        "6.1.3 Quiz: What Is a Circle?",
        "6.2.3 Quiz: Congruent Chords",
        "6.2.4 Quiz: Chords and Perpendicular Radii",
        "6.2.5 Quiz: Diameter of a Circle",
        "6.3.3 Quiz: Arc Types and Measure",
        "6.4.3 Quiz: Congruent Chords and Circle Angle Measure",
        "6.5.3 Quiz: Inscribed Angles",
        "6.5.4 Quiz: Intersecting Chord Theorem",
        "6.6.3 Quiz: Secant-Secant Angles",
        "6.6.4 Quiz: Tangent-Chord Angles",
        "6.6.5 Quiz: Tangent-Tangent Angles and Their Intercepted Arcs",
        "6.7.3 Quiz: Circumference of a Circle",
        "6.7.4 Quiz: Arc Length",
        "6.8.3 Quiz: Area of a Circle",
        "6.8.4 Quiz: Area of a Sector",
        "6.8.5 Practice: Modeling: Stained Glass Window",
        "6.9.3 Quiz: Circles and Triangles",
        "6.9.4 Journal: Similar Circles",
        "6.10.3 Quiz: Circles and Polygons",
        "6.11.3 Test (CST): Circles Without Coordinates",
        "7.1.2 Exam: Semester 1 Exam"
    ],
    "Geometry B": [
        "1.1.3 Quiz: Midpoint Formula",
        "1.2.3 Quiz: The Distance Formula",
        "1.2.4 Journal: The Distance Formula",
        "1.3.3 Quiz: Patterns and Lines",
        "1.4.3 Quiz: Computing Slope",
        "1.4.4 Practice: Modeling: The Rescue Ship",
        "1.5.3 Quiz: Equations of Lines — Part I",
        "1.5.4 Quiz: Equations of Lines — Part II",
        "1.6.3 Quiz: Equations of Parallel and Perpendicular Lines and Proofs",
        "1.7.3 Quiz: Coordinate Geometry with Polygons",
        "1.8.3 Quiz: Area of a Triangle",
        "1.9.3 Quiz: Area and Perimeter of Polygons",
        "1.10.3 Test (CST): Coordinate Geometry",
        "2.1.3 Quiz: Linear Equations",
        "2.1.4 Quiz: What Is a Conic Section?",
        "2.2.3 Quiz: Geometry of Circles and Ellipses",
        "2.2.4 Quiz: Geometry of Hyperbolas and Parabolas",
        "2.3.3 Quiz: Circles Centered at the Origin",
        "2.3.4 Quiz: Circles Not Centered at the Origin",
        "2.4.3 Quiz: Parabolas with Vertices at the Origin",
        "2.4.4 Quiz: Parabolas with Vertices Not at the Origin",
        "2.4.5 Quiz: Converting Parabolic Equations",
        "2.6.3 Test (CST): Conic Sections",
        "3.1.2 Quiz: Constructions",
        "3.3.2 Quiz: Impossible Problems from Antiquity",
        "3.4.2 Quiz: Transformations",
        "3.4.3 Journal: Transformations",
        "3.5.2 Quiz: Symmetry",
        "3.7.4 Test (TST): Constructions and Transformations",
        "4.1.2 Quiz: Three Dimensions",
        "4.2.2 Quiz: What Is a Polyhedron?",
        "4.3.2 Quiz: Cylinders and Cones",
        "4.4.2 Quiz: Platonic Solids",
        "4.5.3 Quiz: Surface Area of Regular Prisms and Pyramids",
        "4.5.4 Quiz: Surface Area of Right Cylinders and Cones",
        "4.6.3 Quiz: Volume of Prisms, Cylinders, and Cubes",
        "4.6.4 Quiz: Volume of Cones, Cylinders, and Pyramids",
        "4.6.5 Journal: Volume",
        "4.7.3 Quiz: Spheres",
        "4.8.3 Quiz: Similar Solids",
        "4.10.3 Test (CST): Three-Dimensional Solids",
        "5.1.3 Quiz: Probability",
        "5.2.3 Quiz: Probability of Independent and Dependent Events",
        "5.3.3 Quiz: Conditional Probability",
        "5.4.3 Quiz: Two-Way Frequency Tables",
        "5.4.4 Practice: Two-Way Frequency Tables",
        "5.5.3 Quiz: Permutations and Combinations",
        "5.6.3 Test (CST): Applications of Probability",
        "6.1.2 Exam: Semester 2 Exam"
    ],
    "Health": [
        "1.1.2 Quiz: What Is Health?",
        "1.1.4 Quiz: Taking Control of Your Health",
        "1.2.2 Quiz: Stress Management and Self-Esteem",
        "1.2.4 Quiz: Influences on Mental and Emotional Health",
        "1.3.2 Quiz: Suicide",
        "1.3.4 Quiz: Violence and Gang Involvement",
        "1.4.3 Quiz: Communication Strategies",
        "1.5.2 Test (CST): Mental and Emotional Health",
        "2.0.1 Pretest: Pretest",
        "2.1.2 Quiz: Physical Fitness",
        "2.1.4 Quiz: Good Nutrition",
        "2.2.2 Quiz: Evaluating Health Products, Practices, and Services",
        "2.2.4 Quiz: Eating Disorders",
        "2.3.3 Quiz: Setting Goals and Formulating a Plan",
        "2.4.2 Test (CST): Fitness and Nutrition",
        "3.0.1 Pretest: Pretest",
        "3.1.2 Quiz: Alcohol, Tobacco, and Other Drugs",
        "3.1.4 Quiz: Influences on Drug Usage",
        "3.2.2 Quiz: Communicating About Drugs",
        "3.2.4 Quiz: Resources for Protection Against Drug Abuse",
        "3.3.3 Quiz: Advocating Against ATOD Use",
        "3.4.2 Test (CST): Drugs",
        "4.0.1 Pretest: Pretest",
        "4.1.2 Quiz: Communicable Diseases",
        "4.1.4 Quiz: Noncommunicable and Chronic Diseases",
        "4.2.2 Quiz: Public Health Policies",
        "4.2.4 Quiz: Good Hygiene",
        "4.3.3 Quiz: Impact of Technology on Health",
        "4.4.2 Test (CST): Disease",
        "5.0.1 Pretest: Pretest",
        "5.1.2 Quiz: Personal Safety",
        "5.1.4 Quiz: Make Decisions to Avoid Injuries",
        "5.2.2 Quiz: Public Policy and Your Safety",
        "5.2.4 Quiz: First Aid",
        "5.4.2 Test (CST): Injuries",
        "6.0.1 Pretest: Pretest",
        "6.1.2 Quiz: Reproductive Systems",
        "6.1.4 Quiz: Safe and Healthy Relationships",
        "6.2.2 Quiz: Practicing Abstinence",
        "6.2.4 Quiz: Online Safety",
        "6.3.3 Quiz: Abusive Relationships and Sexual Assault",
        "6.4.2 Quiz: STIs/STDs and Contraceptive Methods",
        "6.4.4 Quiz: Pregnancy and Parenting",
        "6.5.2 Test (CST): Sexual Health",
        "7.1.2 Exam: Semester Wrap Up"
    ],
    "Mathematics of Personal Finance A": [
        "1.1.3 Quiz: Money Defined",
        "1.2.3 Quiz: How Money Is Created",
        "1.3.3 Quiz: Inflation and Recession",
        "1.4.3 Quiz: The National and Global Debt",
        "1.5.3 Quiz: Other Forms of Currency",
        "1.6.2 Practice: What Is Money?",
        "1.6.3 Discuss: Group Discussion",
        "1.6.4 Test (CST): What Is Money?",
        "2.1.3 Quiz: Types of Wages",
        "2.2.3 Quiz: Compensation Packages",
        "2.3.3 Quiz: Piece Rate",
        "2.4.3 Quiz: Linear Equations and Wages",
        "2.5.3 Quiz: Percentages and Commission",
        "2.6.3 Quiz: Take-Home Pay: Required Deductions",
        "2.7.3 Quiz: Take-Home Pay: Optional Deductions",
        "2.8.3 Quiz: Income and Career",
        "2.9.3 Quiz: Cost of Living and Budget",
        "2.10.2 Practice: Income and Budgeting",
        "2.10.3 Discuss: Group Discussion",
        "2.10.4 Test (CST): Income and Budgeting",
        "3.1.3 Quiz: Taxable Income",
        "3.2.3 Quiz: Itemized Deductions",
        "3.3.3 Quiz: Tax Brackets",
        "3.4.3 Quiz: Submitting Your Tax Form",
        "3.5.2 Practice: Income Tax",
        "3.5.3 Discuss: Group Discussion",
        "3.5.4 Test (CST): Income Tax",
        "4.1.3 Quiz: Simple Interest",
        "4.2.3 Quiz: Exponential Growth",
        "4.3.3 Quiz: Compound Interest",
        "4.4.3 Quiz: Rule of 72",
        "4.5.3 Quiz: Checking Accounts",
        "4.6.3 Quiz: Balancing Your Checkbook",
        "4.7.3 Quiz: Comparing Checking Accounts",
        "4.8.3 Quiz: Savings Accounts",
        "4.9.3 Quiz: Comparing Savings Accounts",
        "4.10.2 Practice: Checking and Savings",
        "4.10.3 Discuss: Group Discussion",
        "4.10.4 Test (CST): Checking and Savings",
        "5.1.3 Quiz: Sales Tax",
        "5.2.3 Quiz: Coupons, Rebates, and Sales",
        "5.3.3 Quiz: Marketing",
        "5.4.3 Quiz: Credit Cards",
        "5.5.3 Quiz: Calculating Credit Card Interest",
        "5.6.3 Quiz: Tracking Payments and Purchases",
        "5.7.3 Quiz: Comparing Credit Cards",
        "5.8.3 Quiz: Credit Scores",
        "5.9.3 Quiz: Bankruptcy",
        "5.10.2 Practice: Purchasing and Credit",
        "5.10.3 Discuss: Group Discussion",
        "5.10.4 Test (CST): Purchasing and Credit",
        "6.1.3 Quiz: Single and Payday Loans",
        "6.2.3 Quiz: Installment Loans and Layaway",
        "6.3.3 Quiz: Monthly Payment",
        "6.4.3 Quiz: Loan Pre-Approvals",
        "6.5.3 Quiz: Deferred Payments",
        "6.6.3 Quiz: Paying Off",
        "6.7.3 Quiz: Prepayment",
        "6.8.2 Practice: Loans and Payments",
        "6.8.3 Discuss: Group Discussion",
        "6.8.4 Test (CST): Loans and Payments",
        "7.1.2 Exam: Semester 1 Exam"
    ],
    "Media Literacy": [
        "1.1.2 Quiz: Understanding the Study",
        "1.1.4 Quiz: Understanding the Study",
        "1.1.5 Practice: Reading More Than Words",
        "1.2.4 Quiz: Understanding the Reading",
        "1.2.6 Quiz: Understanding the Study",
        "1.2.7 Discuss: What's Your Opinion? Technological Shifts",
        "1.3.2 Quiz: Understanding the Study",
        "1.3.4 Quiz: Understanding the Reading",
        "1.3.6 Quiz: Understanding the Study",
        "1.3.7 Practice: Best Blog Ever!",
        "1.4.2 Quiz: Understanding the Study",
        "1.4.4 Quiz: Understanding the Study",
        "1.4.5 Project: Eat Your Media!",
        "1.5.3 Test (TST): What Is a Networked World?",
        "2.1.2 Quiz: Understanding the Study",
        "2.1.4 Quiz: Understanding the Study",
        "2.2.2 Quiz: Understanding the Study",
        "2.2.6 Quiz: Understanding the Study",
        "2.2.7 Discuss: What's Your Opinion? The Reality of the News",
        "2.3.2 Quiz: Understanding the Study",
        "2.3.6 Quiz: Understanding the Study",
        "2.3.7 Practice: Make Your Own Paid Advertisement",
        "2.4.2 Quiz: Understanding the Study",
        "2.4.4 Quiz: Understanding the Study",
        "2.4.5 Project: Advertisement Campaign",
        "2.5.3 Test (TST): How Do You Read in a Networked World?",
        "3.1.2 Quiz: Understanding the Study",
        "3.2.2 Quiz: Understanding the Study",
        "3.2.4 Quiz: Understanding the Reading",
        "3.2.6 Quiz: Understanding the Study",
        "3.3.2 Quiz: Understanding the Study",
        "3.3.6 Quiz: Understanding the Study",
        "3.4.2 Quiz: Understanding the Study",
        "3.4.4 Quiz: Understanding the Study",
        "3.4.5 Project: Who Are You in a Networked World?",
        "3.5.3 Test (TST): Who Are You in a Networked World?",
        "4.1.2 Quiz: Understanding the Study",
        "4.1.4 Quiz: Understanding the Study",
        "4.1.5 Practice: Creative Review",
        "4.2.2 Quiz: Understanding the Study",
        "4.2.4 Quiz: Understanding the Reading",
        "4.2.6 Quiz: Understanding the Study",
        "4.3.4 Quiz: Understanding the Reading",
        "4.3.6 Quiz: Understanding the Study",
        "4.3.7 Practice: Imagine a World",
        "4.4.2 Quiz: Understanding the Study",
        "4.4.4 Quiz: Understanding the Study",
        "4.4.5 Project: Citizen Reporter",
        "4.5.3 Test (TST): What Do You Create in a Networked World? Part 1",
        "5.1.2 Quiz: Understanding the Study",
        "5.1.5 Practice: A Story in Sounds",
        "5.2.2 Quiz: Understanding the Study",
        "5.2.4 Quiz: Understanding the Reading",
        "5.3.2 Quiz: Understanding the Study",
        "5.3.4 Quiz: Understanding the Reading",
        "5.3.6 Quiz: Understanding the Study",
        "5.3.7 Practice: If I Were a Cyberstar, I'd Use My Power To...",
        "5.4.2 Quiz: Understanding the Study",
        "5.4.4 Quiz: Understanding the Study",
        "5.4.5 Project: You Create the Future",
        "5.5.3 Test (TST): What Do You Create in a Networked World? Part 2",
        "6.1.3 Final Exam: Final Exam"
    ],
    "Modern World History A": [
        "1.1.3 Quiz: Introduction to Modern World History",
        "1.2.3 Quiz: Understanding Historiography",
        "1.2.6 Quiz: Chronological Thinking",
        "1.3.2 Quiz: Primary and Secondary Sources",
        "1.3.5 Quiz: Reliability, Credibility, and Contextualization",
        "1.4.2 Test (CST): Welcome to Modern World History",
        "2.1.3 Quiz: The Scientific Revolution",
        "2.1.5 Quiz: The Age of Enlightenment",
        "2.2.3 Quiz: Great Britain's Industrial Revolution",
        "2.2.5 Quiz: Industrialization Spreads",
        "2.3.3 Quiz: Industrialization and the Economy",
        "2.3.5 Quiz: Social Changes",
        "2.3.7 Quiz: Responses to Industrialization",
        "2.4.2 Test (CST): Revolutions in Science and Industry",
        "3.1.3 Quiz: The Emergence of Modern Democracy",
        "3.1.5 Quiz: Revolution and Democracy in North America",
        "3.1.7 Quiz: The French Revolution",
        "3.2.2 Quiz: The Haitian Revolution",
        "3.2.5 Quiz: Independence Movements in Latin America",
        "3.3.3 Quiz: The Abolition Movement",
        "3.3.6 Quiz: Women's Rights and the Suffrage Movement",
        "3.4.2 Test (CST): Political Revolutions and the Expansion of Rights",
        "4.1.3 Quiz: Islamic Land Empires",
        "4.1.5 Quiz: External Pressures in China and Japan",
        "4.2.3 Quiz: Motivations for Imperialism",
        "4.2.6 Quiz: Colonialism in India, Indochina, and the South Pacific",
        "4.2.8 Quiz: The Scramble for Africa",
        "4.3.3 Quiz: Consolidation of Nation-States",
        "4.3.6 Quiz: Lead-Up to War",
        "4.4.3 Quiz: Key Events of the War",
        "4.4.6 Quiz: The Russian Revolution",
        "4.4.8 Quiz: The End of War",
        "4.5.2 Test (CST): Imperialism, Nationalism, and the Great War",
        "5.1.2 Exam: Semester 1 Exam"
    ],
    "Multicultural Studies": [
        "1.1.3 Quiz: Aspects of Identity",
        "1.1.4 Discuss: What Is Your Identity?",
        "1.2.3 Quiz: Family History and Identity",
        "1.2.4 Practice: Family History and Identity",
        "1.3.3 Quiz: Social Identity",
        "1.3.4 Journal: My Social Identities",
        "1.4.3 Quiz: Group Conflict and Interaction",
        "1.4.4 Discuss: Group Conflict and Interaction",
        "1.5.2 Test (CST): Identity",
        "2.1.3 Quiz: What Is Culture?",
        "2.1.4 Journal: What Cultures Do You Belong To?",
        "2.2.3 Quiz: Culture and Perspective",
        "2.2.4 Discuss: Culture and Perspective",
        "2.3.3 Quiz: Cultural Diversity",
        "2.3.4 Practice: Cultural Plunge",
        "2.4.3 Quiz: Cross-Cultural Communication",
        "2.4.4 Discuss: Courageous Dialogue",
        "2.5.2 Test (CST): Culture in a Multicultural Society",
        "3.1.3 Quiz: The Origins of Race and Racism",
        "3.1.4 Discuss: The Origins of Race and Racism",
        "3.2.3 Quiz: Native People in This Land",
        "3.2.4 Discuss: Whose Home Is It?",
        "3.3.1 Journal: Respond: How Did Your Family Come to the United States?",
        "3.3.4 Quiz: Immigration and Identity",
        "3.3.5 Practice: Is This Gold Mountain?",
        "3.4.3 Quiz: Am I an American?",
        "3.4.4 Journal: How Has Race Affected My Life?",
        "3.5.2 Test (CST): Race and Identity",
        "4.1.3 Quiz: Deconstructing the Media",
        "4.1.4 Discuss: Break It Down",
        "4.2.3 Quiz: Stereotypes in Early Media",
        "4.2.4 Journal: Deconstructing Early Media",
        "4.3.3 Quiz: The Struggle for Self-Representation in the Media",
        "4.3.4 Practice: What's the Story?",
        "4.4.3 Quiz: Race in Today's Media: What's the Message?",
        "4.4.4 Discuss: What Do You Believe?",
        "4.5.2 Test (CST): The Media, Race, and Identity",
        "4.5.3 Test (TST): The Media, Race, and Identity",
        "5.1.3 Quiz: Racism Today",
        "5.1.4 Journal: Is This a New Day?",
        "5.2.3 Quiz: Fighting for Rights Today",
        "5.2.4 Practice: The Fight for Rights",
        "5.3.3 Quiz: Conversations about Race",
        "5.3.4 Discuss: Does Race Still Matter?",
        "5.4.3 Quiz: Ending Racism in Your Life",
        "5.4.4 Discuss: What Would You Do?",
        "5.5.2 Test (CST): Understanding and Addressing Racism in the United States",
        "6.1.2 Exam: Exam"
    ],
    "Physical Education": [
        "1.1.2 Practice: Commitment Statement",
        "1.1.3 Discuss: Meet Your Team",
        "1.1.4 Quiz: Online P.E.",
        "1.2.1 Log: Fitness Log # 1",
        "1.2.2 Log: Fitness Log # 2",
        "1.2.3 Log: Fitness Log # 3",
        "1.2.4 Log: Fitness Log # 4",
        "1.2.5 Log: Fitness Log # 5",
        "1.2.6 Log: Fitness Log # 6",
        "1.3.3 Practice: Design Your Routine",
        "1.3.4 Quiz: Warm It Up, Cool It Down",
        "1.4.3 Practice: Setting and Reaching Goals",
        "1.4.4 Quiz: Setting Fitness Goals",
        "1.5.3 Quiz: Career and Educational Options",
        "1.6.2 Test (CST): P.E. Designed for Me",
        "2.1.4 Quiz: Your Fitness Needs",
        "2.2.3 Practice: Playing It Safe",
        "2.2.4 Quiz: Safety Factors",
        "2.3.4 Quiz: Don't Hurt Yourself",
        "2.4.3 Discuss: Nutritious and Delicious",
        "2.4.4 Practice: Nobody's Perfect",
        "2.4.5 Quiz: Health Practices",
        "2.5.2 Test (CST): Computer-Scored Test",
        "3.1.3 Practice: Be Your Own Heart Rate Monitor",
        "3.1.4 Quiz: Work Your Heart Out Quiz",
        "3.2.3 Explore: Have You Ever Played?",
        "3.2.4 Quiz: Join the Team Quiz",
        "3.3.3 Practice: My Team of Choice",
        "3.3.4 Quiz: Team Concepts Quiz",
        "3.4.3 Journal: Am I a Good Sport?",
        "3.4.4 Discuss: Competitive Versus Aggressive",
        "3.4.5 Quiz: Sportsmanship Quiz",
        "3.5.2 Test (CST): Great for the Heart",
        "4.1.3 Practice: Strength Training",
        "4.1.4 Quiz: Muscle Madness",
        "4.2.3 Discuss: Safe to Get Buff",
        "4.2.4 Journal: Anaerobic for Life",
        "4.2.5 Quiz: Time for Anaerobics",
        "4.3.3 Practice: For the Sport of It",
        "4.3.4 Quiz: Individual Sports",
        "4.4.4 Quiz: Sports Downfalls",
        "4.5.2 Test (CST): Fit as a Fiddle",
        "5.1.4 Journal: Leaving the Comfort Zone",
        "5.1.5 Quiz: Outdoor Fitness Fun",
        "5.2.3 Practice: A Weekend Away",
        "5.2.4 Quiz: Have Fun and Be Careful",
        "5.3.3 Explore: Find a Fit for You",
        "5.3.4 Quiz: Adventure Activities",
        "5.4.3 Quiz: Continued Athleticism",
        "5.5.2 Test (CST): Fitness Adventure",
        "6.1.2 Exam: Semester Exam"
    ],
    "Physical Science A": [
        "1.1.2 Quiz: What is Science?",
        "1.1.4 Quiz: Introduction to Physical Science",
        "1.2.2 Quiz: Scientific Investigations",
        "1.2.4 Quiz: Modeling",
        "1.2.6 Quiz: Engineering",
        "1.3.2 Test (CST): Science and Engineering",
        "2.1.2 Quiz: Types of Energy",
        "2.1.4 Quiz: Conservation of Energy",
        "2.1.5 Practice: Conservation of Energy",
        "2.2.2 Quiz: Thermal Energy and Matter",
        "2.2.4 Quiz: Transfer of Thermal Energy",
        "2.4.2 Test (CST): Energy",
        "3.1.2 Quiz: Newton’s Laws of Motion",
        "3.1.4 Quiz: Noncontact Forces",
        "3.2.2 Quiz: Momentum",
        "3.3.2 Test (CST): Forces",
        "4.1.2 Quiz: Electricity",
        "4.1.4 Quiz: Magnetism",
        "4.2.2 Quiz: Electromagnetism",
        "4.2.4 Quiz: Electromagnetism",
        "4.3.2 Test (CST): Electromagnets",
        "5.1.2 Exam: Semester Exam"
    ],
    "Physical Science B": [
        "1.1.2 Quiz: Wave Properties",
        "1.1.4 Quiz: Wave Interactions",
        "1.2.2 Quiz: Electromagnetic Radiation",
        "1.2.5 Quiz: Wave-Particle Duality",
        "1.2.6 Practice: Wave-Particle Duality",
        "1.3.2 Quiz: Introduction to Wave Technology",
        "1.3.4 Quiz: Digital Technology",
        "1.3.5 Practice: Applications of Waves",
        "1.4.2 Test (CST): Waves",
        "2.1.2 Quiz: Types of Matter",
        "2.1.4 Quiz: The Periodic Table",
        "2.1.6 Quiz: Chemical Bonds",
        "2.2.2 Quiz: Properties of Matter",
        "2.2.3 Explore: Properties of Matter",
        "2.2.5 Quiz: Properties of Matter",
        "2.3.2 Test (CST): Structure and Properties of Matter",
        "3.1.2 Quiz: Chemical Equations",
        "3.1.4 Quiz: Types of Chemical Reactions",
        "3.1.5 Practice: Describing Chemical Reactions",
        "3.2.2 Quiz: Energy of Chemical Reactions",
        "3.2.5 Quiz: Reaction Rates",
        "3.2.7 Quiz: Dynamic Equilibrium",
        "3.3.2 Test (CST): Chemical Reactions",
        "4.1.2 Quiz: Fission and Fusion",
        "4.1.4 Quiz: Radioactive Decay",
        "4.3.2 Test (CST): Nuclear Reactions",
        "5.1.2 Exam: Semester Exam"
    ],
    "U.S. Government": [
        "1.1.3 Quiz: Working with Sources",
        "1.1.5 Quiz: Constructing Arguments",
        "1.1.6 Practice: Argue Your Case",
        "1.2.2 Quiz: How Governments Function",
        "1.2.3 Discuss: The Purposes of Government",
        "1.2.5 Quiz: Types of Democracies",
        "1.2.6 Practice: Comparing Governments",
        "1.3.2 Quiz: Inspiration for Independence",
        "1.3.5 Quiz: Early American Governments",
        "1.3.6 Practice: Examining the Founding Principles",
        "1.4.2 Test (CST): Introduction to U.S. Government",
        "2.1.2 Quiz: Arguments and Compromises",
        "2.1.4 Quiz: Ratifying the Constitution",
        "2.1.5 Discuss: Whose Side Are You On?",
        "2.2.3 Quiz: The Parts of the Constitution",
        "2.2.6 Quiz: Principles of the Constitution",
        "2.2.7 Practice: Applying Constitutional Principles",
        "2.3.2 Quiz: The Division of Powers",
        "2.3.4 Quiz: Federalism in Action",
        "2.4.3 Test (TST): The U.S. Constitution",
        "3.1.2 Quiz: The Presidency",
        "3.1.3 Journal: The President's Power",
        "3.1.5 Quiz: The Federal Bureaucracy",
        "3.2.2 Quiz: Understanding the Federal Justice System",
        "3.2.5 Quiz: The Supreme Court",
        "3.2.6 Practice: Overturning a Supreme Court Decision",
        "3.3.2 Quiz: The Setup and Powers of Congress",
        "3.3.4 Quiz: The Legislative Process",
        "3.3.5 Practice: Comparing the Branches",
        "3.4.2 Test (CST): Institutions of the Federal Government",
        "4.1.2 Quiz: The Bill of Rights In Depth",
        "4.1.4 Quiz: First Amendment Freedoms",
        "4.1.5 Journal: We Hold These Truths",
        "4.2.2 Quiz: Due Process and Incorporation",
        "4.2.4 Quiz: Liberties in the Court",
        "4.2.5 Practice: Freedom of the Press in Context",
        "4.3.1 Journal: Liberties and Rights",
        "4.3.3 Quiz: Equal Protection",
        "4.3.6 Quiz: Rights for Marginalized Groups",
        "4.4.3 Test (TST): Civil Liberties and Civil Rights",
        "5.1.2 Quiz: Political Parties",
        "5.1.4 Quiz: Interest Groups",
        "5.1.7 Quiz: The Role of the Media",
        "5.1.8 Practice: Leveraging Your Links",
        "5.2.3 Journal: Campaign Finance and Citizens United",
        "5.4.2 Test (CST): Citizen Connections",
        "6.1.2 Quiz: Introduction to Public Policy",
        "6.1.3 Practice: A Case Study",
        "6.2.2 Quiz: Social Policy",
        "6.2.4 Quiz: Domestic Economic Policy",
        "6.2.5 Discuss: The Controversy Over Health Care",
        "6.3.2 Quiz: The Workings of U.S. Foreign Policy",
        "6.3.4 Quiz: The United States in the World",
        "6.4.3 Test (TST): Public Policy",
        "7.1.2 Quiz: American Citizenship",
        "7.1.4 Quiz: The Obligations of a Citizen",
        "7.1.5 Practice: Do We Earn Our Rights?",
        "7.2.2 Quiz: Voting Rights in the United States",
        "7.2.3 Practice: Becoming a Voter",
        "7.2.5 Quiz: Informed Voting",
        "7.2.6 Practice: Voter Turnout and Its Effects",
        "7.3.3 Quiz: Methods of Participation",
        "7.4.2 Test (CST): Civic and Political Participation",
        "8.1.3 Exam: Semester Exam"
    ],
    "U.S. History since the Civil War A": [
        "1.1.5 Quiz: Radical Reconstruction",
        "1.2.2 Quiz: African American Migration",
        "1.3.4 Quiz: Land and Labor in the South",
        "1.3.6 Discuss: Reconstruction: Success or Failure?",
        "1.3.8 Journal: Reflecting on Changing Times",
        "1.4.2 Quiz: Heading West",
        "1.4.4 Quiz: American Indian Troubles",
        "1.4.6 Quiz: Voting Rights for Women",
        "1.4.7 Discuss: The Mythic West",
        "1.5.3 Test (TST): Post Civil War America",
        "2.1.2 Quiz: The Growth of Big Business",
        "2.1.4 Discuss: Robber Barons",
        "2.1.5 Quiz: Leaders of Industry",
        "2.1.8 Practice: Writing About Business and Labor",
        "2.2.2 Quiz: New Immigrants",
        "2.2.4 Quiz: New Immigrants Face Challenges",
        "2.2.5 Discuss: The Plight of Immigrant Workers",
        "2.3.2 Quiz: Transportation at the Turn of the Century",
        "2.3.4 Quiz: Age of Inventions",
        "2.3.5 Journal: I Can't Do Without It!",
        "2.3.7 Quiz: A Changing Culture",
        "2.4.2 Quiz: Government Corruption",
        "2.4.4 Quiz: The \"Other Half\"",
        "2.4.6 Quiz: How the Other Half Lives",
        "2.4.7 Discuss: A Modern How the Other Half Lives",
        "2.5.3 Test (TST): Industrial America",
        "3.2.2 Quiz: Improving the Cities",
        "3.2.4 Quiz: Organized Labor",
        "3.3.2 Quiz: Limits on Big Business",
        "3.3.4 Discuss: Debating Temperance and Prohibition",
        "3.3.5 Quiz: National Groups",
        "3.3.7 Quiz: The Jungle",
        "3.4.2 Quiz: The Results of Plessy v. Ferguson",
        "3.4.4 Quiz: African American Progressives",
        "3.4.6 Journal: The Progressive Reformers",
        "3.5.3 Test (TST): Populism and Progressivism",
        "4.1.2 Quiz: European Colonies in Africa and Asia",
        "4.1.3 Practice: Mapping the Colonies",
        "4.1.5 Quiz: The Pan-African Congress",
        "4.1.7 Quiz: The United States and the World Economy",
        "4.2.2 Quiz: Americans in the Pacific",
        "4.2.5 Quiz: Seeking Influence in China",
        "4.2.7 Quiz: America and Japan",
        "4.3.2 Quiz: The Spanish-American War",
        "4.3.4 Quiz: Arguments about Imperialism",
        "4.3.6 Quiz: U.S. Policy Towards Latin America",
        "4.4.2 Quiz: War Begins in Europe",
        "4.4.4 Quiz: The United States at War",
        "4.4.6 Quiz: The War at Home",
        "4.4.7 Discuss: Civil Liberties against National Security: World War I",
        "4.5.3 Test (TST): The United States in the Age of Imperialism",
        "5.1.3 Final Exam: Semester 1 Exam"
    ],
    "U.S. History since the Civil War B": [
        "1.1.2 Discuss: Questioning Normalcy",
        "1.1.3 Quiz: Returning to Normalcy",
        "1.1.5 Quiz: Anti-Immigrant Beliefs",
        "1.1.7 Quiz: Increased Racism",
        "1.2.2 Quiz: African American Protest",
        "1.2.3 Practice: The UNIA and the NAACP",
        "1.2.5 Quiz: Women Fight for Equality",
        "1.2.7 Quiz: The Harlem Renaissance",
        "1.3.2 Quiz: The End of the Roaring Twenties",
        "1.3.5 Quiz: Franklin Roosevelt and the New Deal",
        "1.4.2 Quiz: War in Europe",
        "1.4.4 Quiz: War in the Pacific",
        "1.4.5 Discuss: A Big Decision",
        "1.4.7 Quiz: The War at Home",
        "1.5.3 Test (TST): Progress and Challenges",
        "2.1.2 Quiz: Start of the Cold War",
        "2.1.4 Quiz: The Iron Curtain",
        "2.1.6 Quiz: Nationalism or Communism?",
        "2.1.7 Discuss: Nationalism or Communism? Share Your Thoughts",
        "2.2.2 Quiz: The Red Scare",
        "2.2.4 Quiz: Cold War Liberalism",
        "2.2.6 Quiz: Duck and Cover!",
        "2.2.7 Practice: Daily Life During the Cold War",
        "2.3.2 Quiz: Equality or Communism?",
        "2.3.4 Quiz: The Legal Strategy",
        "2.3.6 Discuss: Eisenhower, Kennedy, and Civil Rights",
        "2.3.7 Quiz: Mass Movements",
        "2.4.2 Quiz: Culture of Prosperity",
        "2.4.3 Journal: I Can't Do Without It!",
        "2.4.5 Quiz: From City to Suburb",
        "2.5.3 Test (TST): The Cold War Begins",
        "3.1.2 Quiz: A New Time is Coming",
        "3.1.4 Quiz: The Vietnam War and American Politics",
        "3.1.5 Practice: Hawks and Doves",
        "3.1.7 Quiz: The Great Society",
        "3.2.2 Quiz: Black Power",
        "3.2.4 Quiz: More Groups Demand Rights",
        "3.2.6 Quiz: New Gender Roles",
        "3.2.7 Journal: Civil Rights — Mission Completed?",
        "3.3.2 Quiz: Moving South",
        "3.3.4 Quiz: Music and Power",
        "3.3.6 Quiz: Countercultures",
        "3.5.3 Test (TST): Change Is in the Air",
        "4.1.2 Quiz: Conservatives",
        "4.1.3 Discuss: The Rights of Students",
        "4.1.5 Quiz: The Media Generation",
        "4.2.2 Quiz: Information Revolution",
        "4.2.4 Quiz: Energy Issues",
        "4.2.6 Quiz: International Trade",
        "4.2.7 Practice: Essay — Business versus Labor: Outsourcing",
        "4.3.2 Quiz: Life after the Cold War",
        "4.3.4 Quiz: The United States, Terrorism, and Iraq",
        "4.3.5 Discuss: World Police?",
        "4.4.2 Quiz: Obama and Neo-Progressivism",
        "4.4.4 Quiz: Swimming in the Media Sea",
        "4.4.5 Journal: Personal Time Capsule",
        "4.4.7 Quiz: Changes in the American Population",
        "4.5.3 Test (TST): Contemporary Issues",
        "5.1.2 Exam: Semester 2 Exam"
    ]
};
